services:  
  db:
    image: postgres
    container_name: postgres
    user: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - app.env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.base
    container_name: technews-backend
    command: bash -c "
      cd src
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - app_data:/app
    env_file:
      - app.env
    ports:
      - '8000:8000'
    depends_on: 
      db:
          condition: service_healthy
          restart: true
      redis:
        condition: service_started

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/app
    ports:
     - '6379:6379'
  
  celery-worker:
    build: 
      context: .
      dockerfile: ./Dockerfile.worker
    container_name: celery-worker
    command: bash -c "
      cd src
      && python manage.py crawl --limit 500
      && celery -A tech_news worker -l debug --pool=solo"
    volumes:
      - app_data:/app
    env_file:
      - app.env
    depends_on:
      db:
          condition: service_healthy
          restart: true
      redis:
        condition: service_started
  
  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile.base
    container_name: celery-beat
    command: bash -c "
      cd src
      && until celery -A tech_news inspect ping; do 
        echo 'workers not ready'; 
        sleep 1; 
      done \
      && celery -A tech_news beat -l debug"
    volumes:
      - app_data:/app
    env_file:
      - app.env
    depends_on:
      - redis
      - celery-worker

  celery-flower:
    build:
      context: .
      dockerfile: ./Dockerfile.base
    container_name: celery-flower
    command: bash -c "
      cd src \
      && until celery -A tech_news inspect ping; do 
        echo 'workers not ready'; 
        sleep 1; 
      done \
      && celery -A tech_news flower"
    volumes:
      - app_data:/app
    ports:
      - '5555:5555'
    env_file:
      - app.env
    depends_on:
      - redis
      - celery-worker

volumes: 
  pg_data:
  app_data:
  redis_data:
