services:  
  db:
    image: postgres
    container_name: postgres
    user: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=technewsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql2000
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend-base:1.0
    container_name: technews-backend
    command: bash -c "
      cd src
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - app_data:/app
    environment:
      - SECRET_KEY=django-insecure-)g+)1$640e@dzwxfcljf9!%^gf^^6x50qu9sn$%=q0**sq2ixn
      - DB_NAME=technewsdb
      - DB_USER=postgres
      - DB_PASSWORD=psql2000
      - DB_HOST=postgres
      - DB_PORT=5432    
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on: 
      db:
          condition: service_healthy
          restart: true
      redis:
        condition: service_started

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/app
    ports:
     - '6379:6379'
  
  celery-worker:
    image: backend-base:1.0
    container_name: celery-worker
    command: bash -c "
      cd src
      && celery -A tech_news worker -l debug --pool=solo"
    volumes:
      - app_data:/app
    environment:
      - SECRET_KEY=django-insecure-)g+)1$640e@dzwxfcljf9!%^gf^^6x50qu9sn$%=q0**sq2ixn
      - DB_NAME=technewsdb
      - DB_USER=postgres
      - DB_PASSWORD=psql2000
      - DB_HOST=postgres
      - DB_PORT=5432    
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  
  celery-beat:
    image: backend-base:1.0
    container_name: celery-beat
    command: bash -c "
      cd src
      && celery -A tech_news beat -l debug"
    volumes:
      - app_data:/app
    environment:
      - SECRET_KEY=django-insecure-)g+)1$640e@dzwxfcljf9!%^gf^^6x50qu9sn$%=q0**sq2ixn
      - DB_NAME=technewsdb
      - DB_USER=postgres
      - DB_PASSWORD=psql2000
      - DB_HOST=postgres
      - DB_PORT=5432    
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

  celery-flower:
    image: backend-base:1.0
    container_name: celery-flower
    command: bash -c "
      cd src \
      && until timeout 10s celery -A tech_news inspect ping; do 
        echo 'workers not ready'; 
        sleep 1; 
      done \
      && celery -A tech_news flower"
    volumes:
      - app_data:/app
    ports:
      - '5555:5555'
    environment:
      - SECRET_KEY=django-insecure-)g+)1$640e@dzwxfcljf9!%^gf^^6x50qu9sn$%=q0**sq2ixn
      - DB_NAME=technewsdb
      - DB_USER=postgres
      - DB_PASSWORD=psql2000
      - DB_HOST=postgres
      - DB_PORT=5432    
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker

volumes: 
  pg_data:
  app_data:
  redis_data:
